# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbm_dimitrib11', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChunks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_id', models.IntegerField()),
                ('url_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='audiochunks',
            name='audio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbm_dimitrib11.Audios'),
        ),
        migrations.AddField(
            model_name='translations',
            name='chunk_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fbm_dimitrib11.AudioChunks'),
            preserve_default=False,
        ),
    ]
