# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fbm_dimitrib11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='finishe_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 0, 48, 18, 876268, tzinfo=utc)),
        ),
    ]
