# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbm_dimitrib11', '0002_auto_20171127_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='finishe_date_time',
        ),
        migrations.AddField(
            model_name='conversation',
            name='finished_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
