# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbm_dimitrib11', '0002_auto_20171122_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audios',
            new_name='Audio',
        ),
        migrations.RenameModel(
            old_name='AudioChunks',
            new_name='AudioChunk',
        ),
        migrations.RenameModel(
            old_name='Translations',
            new_name='Transcript',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='translation',
            new_name='text',
        ),
    ]
