# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbm_dimitrib11', '0003_auto_20171123_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', models.CharField(max_length=500)),
                ('locale', models.CharField(max_length=20)),
                ('timezone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
