# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbm_dimitrib11', '0006_audiochunk_audio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiochunk',
            old_name='audio_id',
            new_name='audio',
        ),
    ]
